version: '2.1'
volumes:
    data:
    xserver:
services:
  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    volumes:
      - 'xserver:/tmp/.X11-unix'
  balena-show-website:
    build: .
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - 'data:/data/'
      - 'xserver:/tmp/.X11-unix'
    shm_size: '2gb'
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
    environment:
      WEBSITE_URL: https://status.colournodes.com